# kube-less configuration file

# List of directories to watch for Kubernetes manifests (Deployments, Secrets, ConfigMaps)
manifest_dirs:
  - "./examples/manifests"

# Path to the Container Runtime Interface (CRI) socket
# Common paths:
#   containerd: unix:///run/containerd/containerd.sock
#   CRI-O:      unix:///var/run/crio/crio.sock
cri_socket_path: "unix:///Users/marek/.colima/default/containerd.sock"

# Reconciliation loop interval
sync_interval: "5s"

# Debug API Port
debug_api_port: 8080
